export default [
    {
        name: "NEMESIS MODEL 1",
        price: "$150",
        des: "Special edition from RE3",
        copy: "Detailed, vivid model made by a true fan",
        size: "Dimension 20x50",
        des1: "The best seller character",
        preorder: "500",
        des3: "New arrival",
        copy1: "Limited edition, best model of all time!",
        buttonLabel: "ADD TO CART",
    },
    {
        name: "NEMESIS MODEL 2",
        price: "$150",
        des: "Special edition from RE3",
        copy: "Detailed, vivid model made by a true fan",
        size: "Dimension 20x50",
        des1: "The best seller character",
        preorder: "500",
        des3: "New arrival",
        copy1: "Limited edition, best model of all time!",
        buttonLabel: "ADD TO CART",
    },
    {
        name: "NEMESIS MODEL 3",
        price: "$150",
        des: "Special edition from RE3",
        copy: "Detailed, vivid model made by a true fan",
        size: "Dimension 20x50",
        des1: "The best seller character",
        preorder: "500",
        des3: "New arrival",
        copy1: "Limited edition, best model of all time!",
        buttonLabel: "ADD TO CART",
    },
    {
        name: "NEMESIS MODEL 4",
        price: "$150",
        des: "Special edition from RE3",
        copy: "Detailed, vivid model made by a true fan",
        size: "Dimension 20x50",
        des1: "The best seller character",
        preorder: "500",
        des3: "New arrival",
        copy1: "Limited edition, best model of all time!",
        buttonLabel: "ADD TO CART",
    },
    {
        name: "NEMESIS MODEL 5",
        price: "$150",
        des: "Special edition from RE3",
        copy: "Detailed, vivid model made by a true fan",
        size: "Dimension 20x50",
        des1: "The best seller character",
        preorder: "500",
        des3: "New arrival",
        copy1: "Limited edition, best model of all time!",
        buttonLabel: "ADD TO CART",
    },
];
